run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - prealloc
    - misspell
  disable:
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G104
  govet:
    enable-all: true
  staticcheck:
    checks:
      - all
      - UC1000

issues:
  exclude-use-stock: true
  max-issues-per-linter: 50
  max-same-issues: 10

service:
  golangci-lint-version: 2.1
